{
    "id": "failed",
    "type": "check_file",
    "status": "FAILED",
    "created": "2024-03-18 11:12:05+0000",
    "modified": "2024-03-18 11:12:05+0000",
    "params": {
        "type": "check_file",
        "collection": "article_4_direction",
        "dataset": "article_4_direction_area",
        "original_filename": "article_4_direction_area.geojson",
        "uploaded_filename": "B1E16917-449C-4FC5-96D1-EE4255A79FB1"
    },
    "response": {
        "error": {
            "errCode": "500",
            "errType": "Internal server error",
            "errMsg": "The pipeline failed to run and the file could not be checked",
            "errTime": "2024-03-18 11:12:05+0000"
        }
    }
}